//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountClass
    {
        public accountClass()
        {
            this.fieldDefGroups = new HashSet<fieldDefGroup>();
            this.fieldDefinitions = new HashSet<fieldDefinition>();
        }
    
        public System.Guid accountClassId { get; set; }
        public string accountClassName { get; set; }
        public string accountClassCode { get; set; }
        public int accountClassSortOrder { get; set; }
    
        public virtual ICollection<fieldDefGroup> fieldDefGroups { get; set; }
        public virtual ICollection<fieldDefinition> fieldDefinitions { get; set; }
    }
}
