//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccuLog
    {
        public int logId { get; set; }
        public Nullable<short> logEntryType { get; set; }
        public string applicationName { get; set; }
        public System.Guid runId { get; set; }
        public Nullable<int> eventId { get; set; }
        public Nullable<System.DateTime> entryTime { get; set; }
        public string message { get; set; }
        public string longMessage { get; set; }
    }
}
