//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcculoanDBEntities : DbContext
    {
        public AcculoanDBEntities()
            : base("name=AcculoanDBEntities")
        {
        }
        public AcculoanDBEntities(string Name)
            : base(Name)
        {
        }   
 
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accountClass> accountClasses { get; set; }
        public DbSet<AccuLog> AccuLogs { get; set; }
        public DbSet<accusystemsProperty> accusystemsProperties { get; set; }
        public DbSet<actionAnalysisStatusFilter> actionAnalysisStatusFilters { get; set; }
        public DbSet<actionApplicationStatusFilter> actionApplicationStatusFilters { get; set; }
        public DbSet<actionApprovalStatusFilter> actionApprovalStatusFilters { get; set; }
        public DbSet<actionEvent> actionEvents { get; set; }
        public DbSet<actionEventTimer> actionEventTimers { get; set; }
        public DbSet<actionTimer> actionTimers { get; set; }
        public DbSet<actionTimerDefinition> actionTimerDefinitions { get; set; }
        public DbSet<activitySummary> activitySummaries { get; set; }
        public DbSet<alternateBarcodeMap> alternateBarcodeMaps { get; set; }
        public DbSet<appFunctionList> appFunctionLists { get; set; }
        public DbSet<approval> approvals { get; set; }
        public DbSet<approvalStatu> approvalStatus { get; set; }
        public DbSet<auditDetail> auditDetails { get; set; }
        public DbSet<auditDocumentDetail> auditDocumentDetails { get; set; }
        public DbSet<auditHistory> auditHistories { get; set; }
        public DbSet<bank> banks { get; set; }
        public DbSet<borrowerType> borrowerTypes { get; set; }
        public DbSet<branch> branches { get; set; }
        public DbSet<classCode> classCodes { get; set; }
        public DbSet<coborrower> coborrowers { get; set; }
        public DbSet<collateral> collaterals { get; set; }
        public DbSet<collateralCode> collateralCodes { get; set; }
        public DbSet<collateralField> collateralFields { get; set; }
        public DbSet<collCode> collCodes { get; set; }
        public DbSet<computation> computations { get; set; }
        public DbSet<conditionStatu> conditionStatus { get; set; }
        public DbSet<contact> contacts { get; set; }
        public DbSet<contactType> contactTypes { get; set; }
        public DbSet<creditAnalysisStatu> creditAnalysisStatus { get; set; }
        public DbSet<creditClassification> creditClassifications { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<customerComment> customerComments { get; set; }
        public DbSet<customerField> customerFields { get; set; }
        public DbSet<customerStatu> customerStatus { get; set; }
        public DbSet<customerType> customerTypes { get; set; }
        public DbSet<declinedReason> declinedReasons { get; set; }
        public DbSet<declinedReason_Old> declinedReason_Old { get; set; }
        public DbSet<dh2> dh2 { get; set; }
        public DbSet<dhbackup> dhbackups { get; set; }
        public DbSet<document> documents { get; set; }
        public DbSet<documentActivation> documentActivations { get; set; }
        public DbSet<documentDefinition> documentDefinitions { get; set; }
        public DbSet<documentDependantTask> documentDependantTasks { get; set; }
        public DbSet<documenthistory> documenthistories { get; set; }
        public DbSet<documentSubType> documentSubTypes { get; set; }
        public DbSet<documentTab> documentTabs { get; set; }
        public DbSet<documentTabAccountSecurity> documentTabAccountSecurities { get; set; }
        public DbSet<documentType> documentTypes { get; set; }
        public DbSet<documentUpload> documentUploads { get; set; }
        public DbSet<dtproperty> dtproperties { get; set; }
        public DbSet<exceptedDocument> exceptedDocuments { get; set; }
        public DbSet<exception> exceptions { get; set; }
        public DbSet<exceptionCategory> exceptionCategories { get; set; }
        public DbSet<exceptionComment> exceptionComments { get; set; }
        public DbSet<exceptionDefinition> exceptionDefinitions { get; set; }
        public DbSet<exceptionHistory> exceptionHistories { get; set; }
        public DbSet<exceptionIgnoreLoanStatu> exceptionIgnoreLoanStatus { get; set; }
        public DbSet<fieldDefGroup> fieldDefGroups { get; set; }
        public DbSet<fieldDefinition> fieldDefinitions { get; set; }
        public DbSet<GroupsCustomer> GroupsCustomers { get; set; }
        public DbSet<ImportLog> ImportLogs { get; set; }
        public DbSet<IntegratedSession> IntegratedSessions { get; set; }
        public DbSet<loan> loans { get; set; }
        public DbSet<loanApplication> loanApplications { get; set; }
        public DbSet<loanApplicationCondition> loanApplicationConditions { get; set; }
        public DbSet<loanApplicationHistory> loanApplicationHistories { get; set; }
        public DbSet<loanComment> loanComments { get; set; }
        public DbSet<loanField> loanFields { get; set; }
        public DbSet<loanOfficer> loanOfficers { get; set; }
        public DbSet<loanStatu> loanStatus { get; set; }
        public DbSet<loanType> loanTypes { get; set; }
        public DbSet<MTE_List> MTE_List { get; set; }
        public DbSet<naicsCode> naicsCodes { get; set; }
        public DbSet<noticeLetter> noticeLetters { get; set; }
        public DbSet<noticeParagraph> noticeParagraphs { get; set; }
        public DbSet<noticesToBeSent> noticesToBeSents { get; set; }
        public DbSet<noticeType> noticeTypes { get; set; }
        public DbSet<PolicyDefinition> PolicyDefinitions { get; set; }
        public DbSet<purposeCode> purposeCodes { get; set; }
        public DbSet<region> regions { get; set; }
        public DbSet<RelatedEntityGroup> RelatedEntityGroups { get; set; }
        public DbSet<remoteScanCommTrunk> remoteScanCommTrunks { get; set; }
        public DbSet<remoteScanFolder> remoteScanFolders { get; set; }
        public DbSet<remoteScanQueue> remoteScanQueues { get; set; }
        public DbSet<remoteScanStation> remoteScanStations { get; set; }
        public DbSet<remoteScanStatu> remoteScanStatus { get; set; }
        public DbSet<reportProperty> reportProperties { get; set; }
        public DbSet<scanIssue> scanIssues { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tempGroupsCustomer> tempGroupsCustomers { get; set; }
        public DbSet<tempNoticeSelection> tempNoticeSelections { get; set; }
        public DbSet<tmp_importData> tmp_importData { get; set; }
        public DbSet<typeCode> typeCodes { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<userAccountSecurity> userAccountSecurities { get; set; }
        public DbSet<userbanksecurity> userbanksecurities { get; set; }
        public DbSet<userBranchSecurity> userBranchSecurities { get; set; }
        public DbSet<userGroup> userGroups { get; set; }
        public DbSet<userGroup_user> userGroup_user { get; set; }
        public DbSet<userProfile> userProfiles { get; set; }
    }
}
