//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class actionTimer
    {
        public System.Guid actionTimerId { get; set; }
        public System.Guid loanApplicationId { get; set; }
        public System.Guid actionTimerDefId { get; set; }
        public Nullable<System.DateTime> timerStart { get; set; }
        public Nullable<System.DateTime> timerEnd { get; set; }
    
        public virtual actionTimerDefinition actionTimerDefinition { get; set; }
        public virtual loanApplication loanApplication { get; set; }
    }
}
