//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class actionEvent
    {
        public actionEvent()
        {
            this.actionAnalysisStatusFilters = new HashSet<actionAnalysisStatusFilter>();
            this.actionApplicationStatusFilters = new HashSet<actionApplicationStatusFilter>();
            this.actionApprovalStatusFilters = new HashSet<actionApprovalStatusFilter>();
            this.actionEventTimers = new HashSet<actionEventTimer>();
        }
    
        public System.Guid actionEventId { get; set; }
        public string actionEventName { get; set; }
        public string actionEventDescription { get; set; }
        public bool isLenderAction { get; set; }
        public bool isApproverAction { get; set; }
        public bool isAnalystAction { get; set; }
        public bool selectLender { get; set; }
        public bool selectApprover { get; set; }
        public bool selectAnalyst { get; set; }
        public bool notifyLender { get; set; }
        public bool notifyApprover { get; set; }
        public bool notifyAnalyst { get; set; }
        public bool setApplicationStatus { get; set; }
        public Nullable<System.Guid> applicationStatusId { get; set; }
        public bool setApprovalStatus { get; set; }
        public Nullable<System.Guid> approvalStatusId { get; set; }
        public bool setCreditAnalysisStatus { get; set; }
        public Nullable<System.Guid> creditAnalysisStatusId { get; set; }
        public bool setLoanStatus { get; set; }
        public Nullable<System.Guid> loanStatusId { get; set; }
        public bool setDeclinedException { get; set; }
        public string declinedExceptionDefCode { get; set; }
        public bool selectDeclinedReason { get; set; }
        public bool editConditions { get; set; }
        public bool enforceApprovalLimit { get; set; }
        public bool setLockApplication { get; set; }
        public bool buildApplicationSnapshot { get; set; }
        public string snapshotDocumentCode { get; set; }
        public Nullable<int> analystSortOrder { get; set; }
        public Nullable<int> approverSortOrder { get; set; }
        public Nullable<int> lenderSortOrder { get; set; }
        public bool notifyOther { get; set; }
        public string notifyOtherEmail { get; set; }
        public Nullable<System.Guid> loanTypeId { get; set; }
        public bool requireStatusFilter { get; set; }
    
        public virtual ICollection<actionAnalysisStatusFilter> actionAnalysisStatusFilters { get; set; }
        public virtual ICollection<actionApplicationStatusFilter> actionApplicationStatusFilters { get; set; }
        public virtual ICollection<actionApprovalStatusFilter> actionApprovalStatusFilters { get; set; }
        public virtual ICollection<actionEventTimer> actionEventTimers { get; set; }
    }
}
