//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class approval
    {
        public System.Guid approvalId { get; set; }
        public System.Guid approvalStatusId { get; set; }
        public System.Guid originatingUserId { get; set; }
        public Nullable<System.Guid> assignedApproverId { get; set; }
        public string assignedApproverType { get; set; }
        public Nullable<System.DateTime> dateActedOn { get; set; }
    }
}
