//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditHistory
    {
        public auditHistory()
        {
            this.auditDetails = new HashSet<auditDetail>();
        }
    
        public System.Guid auditId { get; set; }
        public string auditName { get; set; }
        public string auditDescription { get; set; }
        public string userName { get; set; }
        public Nullable<System.DateTime> originationDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<System.Guid> bankId { get; set; }
        public string buildCustomerCommentsYN { get; set; }
        public string auditSize { get; set; }
    
        public virtual ICollection<auditDetail> auditDetails { get; set; }
        public virtual bank bank { get; set; }
    }
}
