//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class computation
    {
        public System.Guid computationId { get; set; }
        public System.Guid exceptionDefId { get; set; }
        public System.Guid docDefId { get; set; }
        public int gracePeriod { get; set; }
        public string statusTypeCheck { get; set; }
    
        public virtual documentDefinition documentDefinition { get; set; }
        public virtual exceptionDefinition exceptionDefinition { get; set; }
    }
}
