//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerStatu
    {
        public System.Guid customerStatusId { get; set; }
        public string customerStatusDescription { get; set; }
        public string customerStatusCode { get; set; }
        public bool isDefault { get; set; }
        public bool isActive { get; set; }
    }
}
