//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.auditDetails = new HashSet<auditDetail>();
            this.coborrowers = new HashSet<coborrower>();
            this.customerComments = new HashSet<customerComment>();
            this.documents = new HashSet<document>();
            this.documentActivations = new HashSet<documentActivation>();
            this.exceptions = new HashSet<exception>();
            this.GroupsCustomers = new HashSet<GroupsCustomer>();
            this.loans = new HashSet<loan>();
        }
    
        public System.Guid customerId { get; set; }
        public string customerName { get; set; }
        public string businessName { get; set; }
        public string customerNumber { get; set; }
        public string TaxId { get; set; }
        public string customerFolder { get; set; }
        public string transferstatus { get; set; }
        public string status { get; set; }
        public Nullable<System.Guid> customerTypeId { get; set; }
        public Nullable<System.DateTime> origdate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<System.Guid> bankId { get; set; }
        public Nullable<int> employee { get; set; }
        public string email { get; set; }
        public string lockCustomerTypeYN { get; set; }
        public string ignoreExceptionsYN { get; set; }
        public Nullable<System.Guid> customerOfficerId { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string phoneHome { get; set; }
        public string phoneWork { get; set; }
        public string phoneMobile { get; set; }
        public string phoneFax { get; set; }
        public Nullable<System.Guid> customerBranchId { get; set; }
        public string customerLastName { get; set; }
        public string customerFirstName { get; set; }
        public string customerMiddleName { get; set; }
        public string salutation { get; set; }
        public string letterName { get; set; }
        public Nullable<System.Guid> classificationId { get; set; }
        public bool lockCustomerName { get; set; }
        public bool lockBusinessName { get; set; }
        public bool lockCustomerNumber { get; set; }
        public bool lockTaxId { get; set; }
        public bool lockStatus { get; set; }
        public bool lockCustomerType { get; set; }
        public bool lockOrigDate { get; set; }
        public bool lockBank { get; set; }
        public bool lockEmployee { get; set; }
        public bool lockEmail { get; set; }
        public bool lockCustomerOfficer { get; set; }
        public bool lockAddress1 { get; set; }
        public bool lockAddress2 { get; set; }
        public bool lockCity { get; set; }
        public bool lockState { get; set; }
        public bool lockZip { get; set; }
        public bool lockPhoneHome { get; set; }
        public bool lockPhoneWork { get; set; }
        public bool lockPhoneMobile { get; set; }
        public bool lockPhoneFax { get; set; }
        public bool lockCustomerBranch { get; set; }
        public bool lockCustomerLastName { get; set; }
        public bool lockCustomerFirstName { get; set; }
        public bool lockCustomerMiddleName { get; set; }
        public bool lockSalutation { get; set; }
        public bool lockLetterName { get; set; }
        public bool lockClassification { get; set; }
        public Nullable<System.Guid> customerStatusId { get; set; }
        public decimal loanLineLimit { get; set; }
        public bool allowExternalAppLink { get; set; }
        public bool lockAllowExternalAppLink { get; set; }
        public int lockCustomer { get; set; }
    
        public virtual ICollection<auditDetail> auditDetails { get; set; }
        public virtual bank bank { get; set; }
        public virtual branch branch { get; set; }
        public virtual ICollection<coborrower> coborrowers { get; set; }
        public virtual customerType customerType { get; set; }
        public virtual loanOfficer loanOfficer { get; set; }
        public virtual ICollection<customerComment> customerComments { get; set; }
        public virtual customerField customerField { get; set; }
        public virtual ICollection<document> documents { get; set; }
        public virtual ICollection<documentActivation> documentActivations { get; set; }
        public virtual ICollection<exception> exceptions { get; set; }
        public virtual ICollection<GroupsCustomer> GroupsCustomers { get; set; }
        public virtual ICollection<loan> loans { get; set; }
    }
}
