//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class declinedReason
    {
        public System.Guid declinedReasonId { get; set; }
        public string declinedReasonDescription { get; set; }
        public string declinedReasonCode { get; set; }
    }
}
