//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public System.Guid documentId { get; set; }
        public Nullable<System.Guid> customerId { get; set; }
        public Nullable<System.Guid> loanId { get; set; }
        public Nullable<System.Guid> documentTypeId { get; set; }
        public Nullable<System.Guid> documentSubTypeId { get; set; }
        public string documentDescription { get; set; }
        public string loanFile { get; set; }
        public string FileName { get; set; }
        public string documentAssociation { get; set; }
        public Nullable<int> documentStatus { get; set; }
        public Nullable<System.DateTime> origdate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<System.DateTime> expdate { get; set; }
        public string email { get; set; }
        public Nullable<int> documentStatusType { get; set; }
        public string documentComment { get; set; }
        public Nullable<System.Guid> documentDefId { get; set; }
        public Nullable<int> remoteScanQueueId { get; set; }
        public System.Guid documentTabId { get; set; }
        public string documentTitle { get; set; }
        public string documentHighlightColor { get; set; }
        public Nullable<bool> nonExpiring { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual documentDefinition documentDefinition { get; set; }
        public virtual documentSubType documentSubType { get; set; }
        public virtual documentType documentType { get; set; }
        public virtual loan loan { get; set; }
        public virtual remoteScanQueue remoteScanQueue { get; set; }
    }
}
