//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentDefinition
    {
        public documentDefinition()
        {
            this.computations = new HashSet<computation>();
            this.documents = new HashSet<document>();
            this.documentTabs = new HashSet<documentTab>();
        }
    
        public System.Guid documentDefId { get; set; }
        public string documentDefType { get; set; }
        public Nullable<System.Guid> documentTypeId { get; set; }
        public Nullable<System.Guid> documentSubTypeId { get; set; }
        public Nullable<System.Guid> customerTypeId { get; set; }
        public Nullable<System.Guid> loanTypeId { get; set; }
        public Nullable<System.Guid> bankId { get; set; }
        public string defaultName { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public bool requireExpdate { get; set; }
        public Nullable<System.DateTime> defaultexpdate { get; set; }
        public bool documentRequired { get; set; }
        public Nullable<int> defaultDocumentStatusType { get; set; }
        public string hideEmployeeFileYN { get; set; }
        public Nullable<int> barcodeKey { get; set; }
        public string hideTabYN { get; set; }
        public Nullable<int> defaultExistingDocumentStatusType { get; set; }
        public string defaultActivationStatus { get; set; }
        public string docDefDocSortBy { get; set; }
        public string docDefHighlightColor { get; set; }
        public bool docDefAllowSchedule { get; set; }
        public int docDefScheduleUnits { get; set; }
        public int docDefSchedulePeriod { get; set; }
        public Nullable<System.DateTime> docDefProcessingDateEnd { get; set; }
        public int docDefDocumentExpireUnits { get; set; }
        public int docDefDocumentExpirePeriod { get; set; }
        public string docDefDocumentTitlePattern { get; set; }
        public Nullable<System.DateTime> docDefNextCreateDate { get; set; }
        public bool isDefault { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual ICollection<computation> computations { get; set; }
        public virtual customerType customerType { get; set; }
        public virtual ICollection<document> documents { get; set; }
        public virtual documentSubType documentSubType { get; set; }
        public virtual documentType documentType { get; set; }
        public virtual loanType loanType { get; set; }
        public virtual ICollection<documentTab> documentTabs { get; set; }
    }
}
