//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentUpload
    {
        public System.Guid documentUploadId { get; set; }
        public string customerName { get; set; }
        public string customerNumber { get; set; }
        public string loanNumber { get; set; }
        public string documentTitle { get; set; }
        public string documentComment { get; set; }
        public string documentFilename { get; set; }
        public string documentCode { get; set; }
        public Nullable<System.DateTime> documentExpDate { get; set; }
        public string uploadSource { get; set; }
        public string uploadedBy { get; set; }
        public string UploadPath { get; set; }
    }
}
