//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentSubType
    {
        public documentSubType()
        {
            this.documents = new HashSet<document>();
            this.documentDefinitions = new HashSet<documentDefinition>();
        }
    
        public System.Guid documentSubTypeId { get; set; }
        public Nullable<System.Guid> documentTypeId { get; set; }
        public string documentSubTypeName { get; set; }
        public string documentCode { get; set; }
        public string subTypeFolderName { get; set; }
        public Nullable<int> subTypeDefaultStatus { get; set; }
        public string subTypeRequireExpDateYN { get; set; }
        public string subTypeHideEmployeeFileYN { get; set; }
        public Nullable<int> subTypeSortOrder { get; set; }
        public string subTypeDescription { get; set; }
        public string subTypeInstruction { get; set; }
        public string subTypeDocSortBy { get; set; }
        public string subTypeHighlightColor { get; set; }
        public bool qcCritical { get; set; }
        public bool allowAccucapture { get; set; }
        public int subTypeScanFlag { get; set; }
    
        public virtual ICollection<document> documents { get; set; }
        public virtual ICollection<documentDefinition> documentDefinitions { get; set; }
        public virtual documentType documentType { get; set; }
    }
}
