//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentActivation
    {
        public System.Guid activationId { get; set; }
        public System.Guid customerId { get; set; }
        public Nullable<System.Guid> loanId { get; set; }
        public Nullable<System.Guid> documentTypeId { get; set; }
        public string activationStatus { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual documentType documentType { get; set; }
        public virtual loan loan { get; set; }
    }
}
