//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class exceptedDocument
    {
        public System.Guid exception_documentId { get; set; }
        public System.Guid exceptionId { get; set; }
        public Nullable<System.Guid> exceptedDocumentId { get; set; }
        public string documentExceptionState { get; set; }
        public System.Guid exceptedDocDefId { get; set; }
    }
}
