//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class exceptionHistory
    {
        public System.Guid historyId { get; set; }
        public System.Guid exceptionId { get; set; }
        public System.Guid changedByUserId { get; set; }
        public string actionTaken { get; set; }
        public System.DateTime dateChanged { get; set; }
        public Nullable<bool> noticeFlag { get; set; }
    
        public virtual exception exception { get; set; }
        public virtual user user { get; set; }
    }
}
