//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class exceptionComment
    {
        public System.Guid exceptionCommentId { get; set; }
        public System.Guid exceptionId { get; set; }
        public string exceptionComment1 { get; set; }
        public Nullable<System.Guid> userId { get; set; }
        public System.DateTime dateAdded { get; set; }
        public System.DateTime dateModified { get; set; }
    
        public virtual exception exception { get; set; }
        public virtual user user { get; set; }
    }
}
