//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class exceptionDefinition
    {
        public exceptionDefinition()
        {
            this.computations = new HashSet<computation>();
            this.exceptions = new HashSet<exception>();
        }
    
        public System.Guid exceptionDefId { get; set; }
        public string exceptionDefName { get; set; }
        public double weight { get; set; }
        public string isGlobalYN { get; set; }
        public System.Guid bankId { get; set; }
        public Nullable<System.Guid> customerTypeId { get; set; }
        public Nullable<System.Guid> loanTypeId { get; set; }
        public string exceptionDefType { get; set; }
        public string computationType { get; set; }
        public string compoundStatement { get; set; }
        public Nullable<System.Guid> defaultAssignedUserId { get; set; }
        public string defaultStatusType { get; set; }
        public int sortOrder { get; set; }
        public string defaultExistingExceptionState { get; set; }
        public string defaultNewExceptionState { get; set; }
        public Nullable<System.Guid> exceptionCategoryId { get; set; }
        public string requireReminderDate { get; set; }
        public Nullable<System.DateTime> defaultReminderDate { get; set; }
        public Nullable<System.Guid> PolicyId { get; set; }
        public Nullable<System.Guid> noticeTypeID { get; set; }
        public Nullable<System.Guid> noticeContactID { get; set; }
        public Nullable<System.DateTime> dateChanged { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public string changedBy { get; set; }
        public Nullable<int> noticeResetDays { get; set; }
        public string noticeReoccuresYN { get; set; }
        public string noticePendingYN { get; set; }
        public Nullable<System.Guid> noticeParagraphID { get; set; }
        public string exceptionDefCode { get; set; }
        public int amountThresholdFlag { get; set; }
        public Nullable<decimal> amountThreshold { get; set; }
        public bool requireLoanMaturityDate { get; set; }
        public Nullable<System.Guid> customCustomerId { get; set; }
        public Nullable<System.Guid> customLoanId { get; set; }
        public int defaultReminderDateGracePeriod { get; set; }
        public bool allowNotificationDefault { get; set; }
        public int taskType { get; set; }
        public string ccNotificationDefault { get; set; }
        public int qcType { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual ICollection<computation> computations { get; set; }
        public virtual customerType customerType { get; set; }
        public virtual ICollection<exception> exceptions { get; set; }
        public virtual exceptionCategory exceptionCategory { get; set; }
        public virtual loanType loanType { get; set; }
        public virtual PolicyDefinition PolicyDefinition { get; set; }
        public virtual user user { get; set; }
    }
}
