//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class exceptionCategory
    {
        public exceptionCategory()
        {
            this.exceptionDefinitions = new HashSet<exceptionDefinition>();
        }
    
        public System.Guid categoryId { get; set; }
        public string categoryName { get; set; }
        public string categoryDescription { get; set; }
        public System.Guid bankId { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual ICollection<exceptionDefinition> exceptionDefinitions { get; set; }
    }
}
