//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        public loan()
        {
            this.auditDetails = new HashSet<auditDetail>();
            this.coborrowers = new HashSet<coborrower>();
            this.collaterals = new HashSet<collateral>();
            this.collaterals1 = new HashSet<collateral>();
            this.documents = new HashSet<document>();
            this.documentActivations = new HashSet<documentActivation>();
            this.exceptions = new HashSet<exception>();
            this.loanComments = new HashSet<loanComment>();
        }
    
        public System.Guid loanId { get; set; }
        public string loanNumber { get; set; }
        public Nullable<System.Guid> customerId { get; set; }
        public Nullable<System.Guid> loanTypeId { get; set; }
        public string loanDescription { get; set; }
        public Nullable<System.Guid> loanOfficerId { get; set; }
        public string loanFolder { get; set; }
        public string transferStatus { get; set; }
        public Nullable<System.Guid> loanStatusId { get; set; }
        public Nullable<System.DateTime> loanClosed { get; set; }
        public Nullable<System.DateTime> loanOrigDate { get; set; }
        public Nullable<System.DateTime> origdate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public string loanAmount { get; set; }
        public string lockLoanTypeYN { get; set; }
        public string ignoreExceptionsYN { get; set; }
        public string isCollateralYN { get; set; }
        public Nullable<System.Guid> loanBranchId { get; set; }
        public string orderNumber { get; set; }
        public string PropertyDesc { get; set; }
        public string isCrossCollateralYN { get; set; }
        public Nullable<System.Guid> primaryCollateralId { get; set; }
        public string coreClassCode { get; set; }
        public string coreCollCode { get; set; }
        public string coreCollateralCode { get; set; }
        public string corePurposeCode { get; set; }
        public string coreTypeCode { get; set; }
        public Nullable<decimal> commitmentAmount { get; set; }
        public string coreNaicsCode { get; set; }
        public Nullable<System.DateTime> loanMaturityDate { get; set; }
        public Nullable<System.Guid> loanClassificationId { get; set; }
    
        public virtual ICollection<auditDetail> auditDetails { get; set; }
        public virtual branch branch { get; set; }
        public virtual ICollection<coborrower> coborrowers { get; set; }
        public virtual ICollection<collateral> collaterals { get; set; }
        public virtual ICollection<collateral> collaterals1 { get; set; }
        public virtual collateralField collateralField { get; set; }
        public virtual customer customer { get; set; }
        public virtual ICollection<document> documents { get; set; }
        public virtual ICollection<documentActivation> documentActivations { get; set; }
        public virtual ICollection<exception> exceptions { get; set; }
        public virtual loanOfficer loanOfficer { get; set; }
        public virtual loanStatu loanStatu { get; set; }
        public virtual loanType loanType { get; set; }
        public virtual ICollection<loanComment> loanComments { get; set; }
        public virtual loanField loanField { get; set; }
    }
}
