//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanApplication
    {
        public loanApplication()
        {
            this.actionTimers = new HashSet<actionTimer>();
        }
    
        public System.Guid loanApplicationId { get; set; }
        public System.Guid loanId { get; set; }
        public string applicationNumber { get; set; }
        public Nullable<System.DateTime> applicationDate { get; set; }
        public Nullable<System.Guid> creditAnalysisStatusId { get; set; }
        public Nullable<decimal> primaryCollateralValue { get; set; }
        public string FICO { get; set; }
        public Nullable<decimal> requestedAmount { get; set; }
        public Nullable<System.DateTime> valuationDate { get; set; }
        public string assignedAnalystType { get; set; }
        public Nullable<System.Guid> assignedAnalystId { get; set; }
        public string assignedLenderType { get; set; }
        public Nullable<System.Guid> assignedLenderId { get; set; }
        public string assignedLoanProcessorType { get; set; }
        public Nullable<System.Guid> assignedLoanProcessorId { get; set; }
        public Nullable<System.Guid> declinedReasonId { get; set; }
        public Nullable<System.Guid> approvalId { get; set; }
        public Nullable<int> nextApplicationNumber { get; set; }
        public string interestRate { get; set; }
        public bool applicationLocked { get; set; }
        public Nullable<decimal> probability { get; set; }
        public Nullable<System.DateTime> estimatedCloseDate { get; set; }
        public string repaymentOption { get; set; }
    
        public virtual ICollection<actionTimer> actionTimers { get; set; }
    }
}
