//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanComment
    {
        public System.Guid loanCommentId { get; set; }
        public Nullable<System.Guid> loanId { get; set; }
        public Nullable<System.Guid> userId { get; set; }
        public Nullable<System.DateTime> commentDate { get; set; }
        public string comment { get; set; }
    
        public virtual loan loan { get; set; }
        public virtual user user { get; set; }
    }
}
