//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanType
    {
        public loanType()
        {
            this.documentDefinitions = new HashSet<documentDefinition>();
            this.exceptionDefinitions = new HashSet<exceptionDefinition>();
            this.loans = new HashSet<loan>();
        }
    
        public System.Guid loanTypeId { get; set; }
        public string loanTypeDescription { get; set; }
        public string loanTypeCode { get; set; }
        public string isCollateralTypeYN { get; set; }
        public System.Guid accountClassId { get; set; }
    
        public virtual ICollection<documentDefinition> documentDefinitions { get; set; }
        public virtual ICollection<exceptionDefinition> exceptionDefinitions { get; set; }
        public virtual ICollection<loan> loans { get; set; }
    }
}
