//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTE_List
    {
        public System.Guid MTEID { get; set; }
        public string TaxID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerNumber { get; set; }
        public string Appendage { get; set; }
    }
}
