//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticeLetter
    {
        public System.Guid LetterID { get; set; }
        public string GroupKeyID { get; set; }
        public Nullable<System.Guid> SentToID { get; set; }
        public string sentToName { get; set; }
        public string headerText { get; set; }
        public string paragraphs { get; set; }
        public string footerText { get; set; }
        public System.DateTime dateCreated { get; set; }
        public System.DateTime dateChanged { get; set; }
        public string changedBy { get; set; }
        public string officerName { get; set; }
    }
}
