//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticesToBeSent
    {
        public string NoticeGroupKey { get; set; }
        public System.Guid exceptionID { get; set; }
        public System.DateTime dateStored { get; set; }
        public string sentBy { get; set; }
        public Nullable<System.Guid> letterID { get; set; }
        public System.Guid sentID { get; set; }
    }
}
