//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyDefinition
    {
        public PolicyDefinition()
        {
            this.exceptionDefinitions = new HashSet<exceptionDefinition>();
        }
    
        public System.Guid PolicyId { get; set; }
        public string PolicyTitle { get; set; }
        public string PolicyDescription { get; set; }
    
        public virtual ICollection<exceptionDefinition> exceptionDefinitions { get; set; }
    }
}
