//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class remoteScanQueue
    {
        public remoteScanQueue()
        {
            this.documents = new HashSet<document>();
        }
    
        public int remoteScanQueueId { get; set; }
        public Nullable<int> remoteScanFoldersId { get; set; }
        public string scanInfoXml { get; set; }
        public string fileName { get; set; }
        public string machineName { get; set; }
        public string scannerLoginName { get; set; }
        public bool hasEmbeddedBarcodes { get; set; }
        public System.DateTime rowInsertTime { get; set; }
        public Nullable<System.DateTime> remoteFileSeenTime { get; set; }
        public Nullable<System.DateTime> failToSeeServerFolderTime { get; set; }
        public Nullable<System.DateTime> failToSeeRemoteFolderTime { get; set; }
        public Nullable<System.DateTime> copyToServerTime { get; set; }
        public Nullable<System.DateTime> failToSeeRemoteFileTime { get; set; }
        public Nullable<System.DateTime> deleteRemoteFileTime { get; set; }
        public Nullable<System.DateTime> failToDeleteTime { get; set; }
        public Nullable<System.DateTime> failToCopyTime { get; set; }
        public string failToCopyLog { get; set; }
        public Nullable<System.DateTime> barcodeProcessingDoneTime { get; set; }
        public Nullable<int> sourceBarcodeRemoteScanQueueId { get; set; }
        public Nullable<System.DateTime> importDoneTime { get; set; }
        public Nullable<System.DateTime> failToImportTime { get; set; }
        public string failToImportLog { get; set; }
        public bool importIsActive { get; set; }
        public string remoteFolderPath { get; set; }
        public Nullable<System.Guid> documentId { get; set; }
        public Nullable<int> ScanID { get; set; }
        public Nullable<int> pagesAdded { get; set; }
        public Nullable<int> pagesDeleted { get; set; }
        public string remoteFilename { get; set; }
        public Nullable<bool> fromAccuCapture { get; set; }
        public Nullable<short> remoteScanStatusCode { get; set; }
        public int accucaptureAssignedDocCount { get; set; }
    
        public virtual ICollection<document> documents { get; set; }
    }
}
