//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class remoteScanCommTrunk
    {
        public remoteScanCommTrunk()
        {
            this.remoteScanFolders = new HashSet<remoteScanFolder>();
        }
    
        public int commTrunkId { get; set; }
        public string commTrunkLabel { get; set; }
        public string commTrunkDescription { get; set; }
    
        public virtual ICollection<remoteScanFolder> remoteScanFolders { get; set; }
    }
}
