//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class remoteScanStation
    {
        public int scanStationId { get; set; }
        public string machineName { get; set; }
        public Nullable<int> remoteScanFoldersId { get; set; }
        public string scanStationDescription { get; set; }
    
        public virtual remoteScanFolder remoteScanFolder { get; set; }
    }
}
