//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportProperty
    {
        public System.Guid reportPropertyId { get; set; }
        public string websiteURL { get; set; }
        public string isGuidYN { get; set; }
        public string displayName { get; set; }
        public string reportsBaseURL { get; set; }
        public string reportServerBaseURL { get; set; }
        public string reportPath { get; set; }
        public Nullable<int> noticeReportRemovalDays { get; set; }
        public string reportServerURL { get; set; }
    }
}
