//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class scanIssue
    {
        public short rowNumber { get; set; }
        public string userLogin { get; set; }
        public string userName { get; set; }
        public string Existing_userLogin { get; set; }
        public string ConvertToRow { get; set; }
    }
}
