//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempNoticeSelection
    {
        public string userName { get; set; }
        public Nullable<System.Guid> exceptionID { get; set; }
        public string exceptionDefName { get; set; }
        public string customerName { get; set; }
        public string contactName { get; set; }
        public string loanNumber { get; set; }
        public string ColLoanNumber { get; set; }
        public string nextDate { get; set; }
        public string selected { get; set; }
        public string verifyException { get; set; }
    }
}
