//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class userGroup
    {
        public System.Guid userGroupId { get; set; }
        public string userGroupName { get; set; }
        public string userGroupCode { get; set; }
        public bool isAnalystGroup { get; set; }
        public bool isApproverGroup { get; set; }
        public bool isLenderGroup { get; set; }
        public bool isLoanProcessorGroup { get; set; }
    }
}
