//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAccountSecurity
    {
        public System.Guid userAccountAccessId { get; set; }
        public System.Guid userId { get; set; }
        public string accountClassCode { get; set; }
        public bool allowRead { get; set; }
        public bool allowEdit { get; set; }
        public bool allowAdd { get; set; }
        public bool allowDelete { get; set; }
        public bool allowDocRead { get; set; }
        public bool allowDocEdit { get; set; }
        public bool allowDocAdd { get; set; }
        public bool allowDocDelete { get; set; }
        public bool allowDocScan { get; set; }
        public bool allowDocScanDelete { get; set; }
        public bool allowDocUpload { get; set; }
        public bool allowDocMoveCopy { get; set; }
        public bool isAdmin { get; set; }
    }
}
