//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class activitySummary
    {
        public System.Guid activitySummaryId { get; set; }
        public System.Guid functionId { get; set; }
        public Nullable<System.Guid> userId { get; set; }
        public int actionType { get; set; }
        public string target { get; set; }
        public System.DateTime actionDate { get; set; }
    }
}
