//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class alternateBarcodeMap
    {
        public System.Guid alternateBarcodeMapId { get; set; }
        public System.Guid documentSubTypeId { get; set; }
        public string barcodeKey { get; set; }
    }
}
