//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class approvalStatu
    {
        public approvalStatu()
        {
            this.actionApprovalStatusFilters = new HashSet<actionApprovalStatusFilter>();
        }
    
        public System.Guid approvalStatusId { get; set; }
        public string approvalStatusDescription { get; set; }
        public string approvalStatusCode { get; set; }
        public bool isDefault { get; set; }
        public bool isActiveApprovalStatus { get; set; }
    
        public virtual ICollection<actionApprovalStatusFilter> actionApprovalStatusFilters { get; set; }
    }
}
