//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditDocumentDetail
    {
        public System.Guid auditDocumentDetailId { get; set; }
        public System.Guid auditDetailId { get; set; }
        public Nullable<System.Guid> documentId { get; set; }
        public System.Guid documentDefId { get; set; }
    }
}
