//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank
    {
        public bank()
        {
            this.auditHistories = new HashSet<auditHistory>();
            this.branches = new HashSet<branch>();
            this.customers = new HashSet<customer>();
            this.documentDefinitions = new HashSet<documentDefinition>();
            this.exceptionCategories = new HashSet<exceptionCategory>();
            this.exceptionDefinitions = new HashSet<exceptionDefinition>();
            this.loanOfficers = new HashSet<loanOfficer>();
            this.userbanksecurities = new HashSet<userbanksecurity>();
        }
    
        public System.Guid bankId { get; set; }
        public string bankName { get; set; }
        public string bankCode { get; set; }
        public string privacyStatement { get; set; }
        public bool isDefault { get; set; }
    
        public virtual ICollection<auditHistory> auditHistories { get; set; }
        public virtual ICollection<branch> branches { get; set; }
        public virtual ICollection<customer> customers { get; set; }
        public virtual ICollection<documentDefinition> documentDefinitions { get; set; }
        public virtual ICollection<exceptionCategory> exceptionCategories { get; set; }
        public virtual ICollection<exceptionDefinition> exceptionDefinitions { get; set; }
        public virtual ICollection<loanOfficer> loanOfficers { get; set; }
        public virtual ICollection<userbanksecurity> userbanksecurities { get; set; }
    }
}
