//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public branch()
        {
            this.customers = new HashSet<customer>();
            this.loans = new HashSet<loan>();
            this.userBranchSecurities = new HashSet<userBranchSecurity>();
        }
    
        public System.Guid branchId { get; set; }
        public System.Guid bankId { get; set; }
        public string branchName { get; set; }
        public string branchCode { get; set; }
        public System.Guid regionId { get; set; }
        public bool isDefault { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual ICollection<customer> customers { get; set; }
        public virtual ICollection<loan> loans { get; set; }
        public virtual ICollection<userBranchSecurity> userBranchSecurities { get; set; }
    }
}
