//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class collateralCode
    {
        public System.Guid collateralCodeId { get; set; }
        public string collateralCodeDescription { get; set; }
        public string collateralCode1 { get; set; }
    }
}
