//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditClassification
    {
        public System.Guid classificationId { get; set; }
        public string classificationName { get; set; }
        public string classificationCode { get; set; }
        public bool displayEmphasis { get; set; }
        public string displayColor { get; set; }
        public string type { get; set; }
        public bool isDefault { get; set; }
    }
}
