//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class dh2
    {
        public System.Guid historyId { get; set; }
        public string userLogin { get; set; }
        public string userName { get; set; }
        public string customerNumber { get; set; }
        public string loanNumber { get; set; }
        public string documentFileName { get; set; }
        public string documentType { get; set; }
        public Nullable<int> pagesAdded { get; set; }
        public Nullable<int> pagesDeleted { get; set; }
        public Nullable<System.DateTime> dateChanged { get; set; }
        public string documentDeletedYN { get; set; }
        public string comment { get; set; }
        public Nullable<int> remoteScanQueueId { get; set; }
        public Nullable<System.Guid> documentId { get; set; }
        public string qcHistory { get; set; }
        public Nullable<System.Guid> inputType { get; set; }
        public Nullable<int> qcStatus { get; set; }
    }
}
