//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentType
    {
        public documentType()
        {
            this.documents = new HashSet<document>();
            this.documentActivations = new HashSet<documentActivation>();
            this.documentDefinitions = new HashSet<documentDefinition>();
            this.documentSubTypes = new HashSet<documentSubType>();
        }
    
        public System.Guid documentTypeId { get; set; }
        public string documentTypeName { get; set; }
        public Nullable<int> typeSortOrder { get; set; }
        public string typeCode { get; set; }
        public string typeActivationStatus { get; set; }
    
        public virtual ICollection<document> documents { get; set; }
        public virtual ICollection<documentActivation> documentActivations { get; set; }
        public virtual ICollection<documentDefinition> documentDefinitions { get; set; }
        public virtual ICollection<documentSubType> documentSubTypes { get; set; }
    }
}
