//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentTab
    {
        public System.Guid documentTabId { get; set; }
        public System.Guid documentDefId { get; set; }
        public System.Guid customerId { get; set; }
        public Nullable<System.Guid> loanId { get; set; }
        public int docTabStatusType { get; set; }
        public string docTabHighlightColor { get; set; }
        public Nullable<bool> docTabAllowSchedule { get; set; }
        public Nullable<int> docTabScheduleUnits { get; set; }
        public Nullable<int> docTabSchedulePeriod { get; set; }
        public Nullable<System.DateTime> docTabProcessingDateEnd { get; set; }
        public Nullable<int> docTabDocumentExpireUnits { get; set; }
        public Nullable<int> docTabDocumentExpirePeriod { get; set; }
        public string docTabDocumentTitlePattern { get; set; }
        public bool docTabOverrideDefinition { get; set; }
        public Nullable<System.DateTime> docTabNextCreateDate { get; set; }
        public bool docTabLockSettings { get; set; }
    
        public virtual documentDefinition documentDefinition { get; set; }
    }
}
