//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class exception
    {
        public exception()
        {
            this.exceptionComments = new HashSet<exceptionComment>();
            this.exceptionHistories = new HashSet<exceptionHistory>();
        }
    
        public System.Guid exceptionId { get; set; }
        public System.Guid exceptionDefId { get; set; }
        public string exceptionState { get; set; }
        public Nullable<System.Guid> assignedUserId { get; set; }
        public System.Guid customerId { get; set; }
        public Nullable<System.Guid> loanId { get; set; }
        public string comment { get; set; }
        public string statusType { get; set; }
        public Nullable<System.DateTime> dateExcepted { get; set; }
        public Nullable<System.DateTime> datePending { get; set; }
        public Nullable<System.DateTime> dateResolved { get; set; }
        public Nullable<System.DateTime> reminderDate { get; set; }
        public Nullable<System.Guid> noticeTypeID { get; set; }
        public Nullable<int> noticeActive { get; set; }
        public Nullable<System.DateTime> noticeSetDate { get; set; }
        public Nullable<System.Guid> noticeContactID { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public Nullable<System.DateTime> dateChanged { get; set; }
        public string changedBy { get; set; }
        public Nullable<int> noticeResetDays { get; set; }
        public string noticeReoccuresYN { get; set; }
        public string noticePendingYN { get; set; }
        public Nullable<System.Guid> noticeParagraphID { get; set; }
        public int reminderDateGracePeriod { get; set; }
        public Nullable<System.Guid> exceptedDocumentId { get; set; }
        public Nullable<bool> allowNotification { get; set; }
        public string ccNotification { get; set; }
        public Nullable<double> ExceptionWeight { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual exceptionDefinition exceptionDefinition { get; set; }
        public virtual loan loan { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<exceptionComment> exceptionComments { get; set; }
        public virtual ICollection<exceptionHistory> exceptionHistories { get; set; }
    }
}
