//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class fieldDefGroup
    {
        public fieldDefGroup()
        {
            this.fieldDefinitions = new HashSet<fieldDefinition>();
        }
    
        public System.Guid fieldDefGroupId { get; set; }
        public string fieldDefGroupName { get; set; }
        public string fieldDefGroupLabel { get; set; }
        public int fieldDefGroupOrder { get; set; }
        public bool fieldDefGroupIsCollateral { get; set; }
        public Nullable<System.Guid> accountClassId { get; set; }
    
        public virtual accountClass accountClass { get; set; }
        public virtual ICollection<fieldDefinition> fieldDefinitions { get; set; }
    }
}
