//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportLog
    {
        public System.Guid Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Severity { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string Details { get; set; }
    }
}
