//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanOfficer
    {
        public loanOfficer()
        {
            this.customers = new HashSet<customer>();
            this.loans = new HashSet<loan>();
            this.users = new HashSet<user>();
        }
    
        public System.Guid officerId { get; set; }
        public string officerName { get; set; }
        public string officerCode { get; set; }
        public Nullable<System.Guid> bankId { get; set; }
        public string officerTitle { get; set; }
        public bool defaultOfficer { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual ICollection<customer> customers { get; set; }
        public virtual ICollection<loan> loans { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
