//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanStatu
    {
        public loanStatu()
        {
            this.actionApplicationStatusFilters = new HashSet<actionApplicationStatusFilter>();
            this.loans = new HashSet<loan>();
        }
    
        public System.Guid statusId { get; set; }
        public string statusDescription { get; set; }
        public string statusCode { get; set; }
        public string isDefaultYN { get; set; }
        public bool isActive { get; set; }
        public bool isApplicationStatus { get; set; }
        public bool isActiveApplicationStatus { get; set; }
        public bool isApprovedApplicationStatus { get; set; }
        public bool isDefaultApplicationStatus { get; set; }
        public System.Guid accountClassId { get; set; }
    
        public virtual ICollection<actionApplicationStatusFilter> actionApplicationStatusFilters { get; set; }
        public virtual ICollection<loan> loans { get; set; }
    }
}
