//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class purposeCode
    {
        public System.Guid purposeCodeId { get; set; }
        public string purposeCodeDescription { get; set; }
        public string purposeCode1 { get; set; }
    }
}
