//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedEntityGroup
    {
        public RelatedEntityGroup()
        {
            this.GroupsCustomers = new HashSet<GroupsCustomer>();
        }
    
        public System.Guid GroupId { get; set; }
        public string EntityRelationship { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual ICollection<GroupsCustomer> GroupsCustomers { get; set; }
    }
}
