//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class remoteScanFolder
    {
        public remoteScanFolder()
        {
            this.remoteScanStations = new HashSet<remoteScanStation>();
        }
    
        public int remoteScanFoldersId { get; set; }
        public string folderPath { get; set; }
        public string folderLabel { get; set; }
        public bool hasEmbeddedBarcodes { get; set; }
        public Nullable<int> commTrunkId { get; set; }
    
        public virtual remoteScanCommTrunk remoteScanCommTrunk { get; set; }
        public virtual ICollection<remoteScanStation> remoteScanStations { get; set; }
    }
}
