//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempGroupsCustomer
    {
        public System.Guid tmpKeyId { get; set; }
        public System.Guid GroupiD { get; set; }
        public System.Guid CustID { get; set; }
        public string UserID { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
