//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class userBranchSecurity
    {
        public System.Guid branchSecurityID { get; set; }
        public Nullable<System.Guid> branchID { get; set; }
        public Nullable<System.Guid> userID { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateChanged { get; set; }
        public string changedBy { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual user user { get; set; }
    }
}
