//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class userbanksecurity
    {
        public System.Guid bankSecurityId { get; set; }
        public Nullable<System.Guid> bankId { get; set; }
        public Nullable<System.Guid> userId { get; set; }
        public Nullable<int> bankaccess { get; set; }
        public Nullable<int> employeefiles { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual user user { get; set; }
    }
}
