//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class userGroup_user
    {
        public System.Guid userGroup_userId { get; set; }
        public System.Guid userGroupId { get; set; }
        public System.Guid userId { get; set; }
    }
}
