//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.exceptions = new HashSet<exception>();
            this.exceptionComments = new HashSet<exceptionComment>();
            this.exceptionDefinitions = new HashSet<exceptionDefinition>();
            this.exceptionHistories = new HashSet<exceptionHistory>();
            this.loanComments = new HashSet<loanComment>();
            this.userbanksecurities = new HashSet<userbanksecurity>();
            this.userBranchSecurities = new HashSet<userBranchSecurity>();
        }
    
        public System.Guid userId { get; set; }
        public string userLogin { get; set; }
        public string userPassword { get; set; }
        public string userFirstName { get; set; }
        public string userLastName { get; set; }
        public string userMiddleInitial { get; set; }
        public string userEmail { get; set; }
        public string userNotes { get; set; }
        public string scanmodule { get; set; }
        public string scannedfilespath { get; set; }
        public short permissionException { get; set; }
        public string inactive { get; set; }
        public Nullable<System.Guid> loanOfficerID { get; set; }
        public decimal loanApprovalLimit { get; set; }
        public bool isApprover { get; set; }
        public bool isAnalyst { get; set; }
        public bool isLender { get; set; }
        public bool isLoanProcessor { get; set; }
        public bool isSuperUser { get; set; }
    
        public virtual ICollection<exception> exceptions { get; set; }
        public virtual ICollection<exceptionComment> exceptionComments { get; set; }
        public virtual ICollection<exceptionDefinition> exceptionDefinitions { get; set; }
        public virtual ICollection<exceptionHistory> exceptionHistories { get; set; }
        public virtual ICollection<loanComment> loanComments { get; set; }
        public virtual loanOfficer loanOfficer { get; set; }
        public virtual ICollection<userbanksecurity> userbanksecurities { get; set; }
        public virtual ICollection<userBranchSecurity> userBranchSecurities { get; set; }
    }
}
